# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-YACSmoke-Plugin-WebList
version:      0.02
version_from: lib/CPAN/YACSmoke/Plugin/WebList.pm
installdirs:  site
requires:
    CPAN::YACSmoke:                0.02_03
    Template::Extract:             0
    Test::More:                    0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
