--- #YAML:1.0
name:                   CPAN-YACSmoke-Plugin-WebList
version:                0.08
abstract:               Website list plugin for CPAN-YACSmoke
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Template::Extract:    0
  Template:             2.00
  WWW::Mechanize:       0
  Test::More:           0.47
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::CPAN::Meta:     0.03
build_requires:
  Test::More:           0.47

provides:
  CPAN::YACSmoke::Plugin::WebList:
    file:     lib/CPAN/YACSmoke/Plugin/WebList.pm
    version:  0.08
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
